export default {
  addContactButton: "#add-contact",
  firstNameField: "#firstName",
  lastNameField: "#lastName",
  birthDateField: "#birthdate",
  emailField: "#email",
  phoneField: "#phone",
  streetField: "#street1",
  cityField: "#city",
  postalCodeField: "#postalCode",
  countryField: "#country",
  submitButton: "#submit",
  error: "#error",
  rowsNewContact: "table tr td:visible",
  header: "h1",
  firstColumnsOfRow: "table tr td:nth-child(2)",
  editButton: "#edit-contact",
  returnButton: "#return",
  deleteButton: "#delete",
  cancelButton: "#cancel",
}
